Emit necessary events
hicommonwealth/edge_bridge pull request #6
Opened 2018-12-22 19:01 UTC by DemiMarie

These had been TODOs in the code.

2018-12-22 19:48 UTC, drewstone reviewed
Looks good! Thanks for the PR!

2018-12-22 19:48 UTC, drewstone commented on src/bridge.rs
> +                         <balances::Module<T>>::decrease_free_balance(&tgt, qty)?;
Looks like the spacing is off by 1.

2018-12-22 19:48 UTC, drewstone requested changes
Looks good! Thanks for the PR!

2018-12-23 00:26 UTC, DemiMarie commented on src/bridge.rs
> +                         <balances::Module<T>>::decrease_free_balance(&tgt, qty)?;
Thank you, fixed.

2018-12-23 11:16 UTC, drewstone approved these changes

2018-12-23 11:16 UTC, merged